version: '3.8'

services:
  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        MAX_HEAP_SIZE: "256M"
        HEAP_NEWSIZE: "128M"
        CASSANDRA_CLUSTER_NAME: "Test Cluster"
        CASSANDRA_DC: "datacenter1"
      restart: always
      volumes:
        - ./out/cassandra_data:/var/lib/cassandra
      healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10

  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:3.11.2
      depends_on:
        cassandra:
          condition: service_healthy
      volumes:
        - ./init.cql:/init.cql
      command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /init.cql"

  rabbitmq:
    image: rabbitmq:3-management    # This version includes the RabbitMQ management plugin
    container_name: rabbitmq
    ports:
      - "5672:5672"                 # Port for RabbitMQ AMQP protocol
      - "15672:15672"               # Port for RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Default username
      RABBITMQ_DEFAULT_PASS: guest  # Default password
    networks:
      - rabbitmq_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      - KEYCLOAK_ADMIN=admin                   # Admin username
      - KEYCLOAK_ADMIN_PASSWORD=admin123       # Admin password
      - KC_DB=postgres                          # Using Postgres as DB
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME_STRICT=false                # Disable strict hostname checks for development
      - KC_PROXY=edge                           # Trust X-Forwarded-* headers
      - KC_IMPORT=/opt/keycloak/data/import/realm-export.json  # Import realm configuration
    ports:
      - 8081:8080
      - 8444:8443
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./realm-config:/opt/keycloak/data/import  # Mount a directory for realm import
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  postgres_data:
